from flask_babel import lazy_gettext as _

FEATURES = [
    {'title': _('Campaign planning'), 'eyebrow': _('Connected capability'), 'description': _('Coordinate briefs, channels, owners, and launch dates in one shared view.')},
    {'title': _('Customer profiles'), 'eyebrow': _('Connected capability'), 'description': _('Create a useful customer view without hiding the source of each data point.')},
    {'title': _('Content library'), 'eyebrow': _('Connected capability'), 'description': _('Organise approved messages, images, and reusable campaign components.')},
    {'title': _('Workflow automation'), 'eyebrow': _('Connected capability'), 'description': _('Reduce manual handovers with clear triggers, checks, and notifications.')},
    {'title': _('Performance insights'), 'eyebrow': _('Connected capability'), 'description': _('Connect activity to outcomes with understandable reports for every stakeholder.')},
    {'title': _('Consent controls'), 'eyebrow': _('Connected capability'), 'description': _('Apply customer preferences consistently across channels and campaign steps.')},
    {'title': _('Audience builder'), 'eyebrow': _('Connected capability'), 'description': _('Define practical segments with readable rules your team can review together.')},
    {'title': _('Experiment tracking'), 'eyebrow': _('Connected capability'), 'description': _('Record hypotheses, variants, decisions, and lessons in one consistent format.')},
    {'title': _('Partner workspace'), 'eyebrow': _('Connected capability'), 'description': _('Give agencies and suppliers the context they need without exposing everything.')},
    {'title': _('Local markets'), 'eyebrow': _('Connected capability'), 'description': _('Adapt global campaigns while preserving local language, timing, and compliance needs.')},
    {'title': _('Review cycles'), 'eyebrow': _('Connected capability'), 'description': _('Keep feedback, approvals, and final decisions attached to the work itself.')},
    {'title': _('Data connectors'), 'eyebrow': _('Connected capability'), 'description': _('Bring selected data into the workspace through transparent, manageable connections.')},
]

SOLUTIONS = [
    {'title': _('Launch campaigns faster'), 'description': _('Replace scattered status meetings with a shared launch plan and visible ownership.')},
    {'title': _('Improve customer relevance'), 'description': _('Use customer context to make each interaction more useful and less repetitive.')},
    {'title': _('Scale content operations'), 'description': _('Create reliable review paths for increasing volumes of regional content.')},
    {'title': _('Strengthen governance'), 'description': _('Make policies actionable with embedded checks, ownership, and evidence.')},
    {'title': _('Support local teams'), 'description': _('Give local teams flexibility while keeping shared standards easy to follow.')},
    {'title': _('Measure useful outcomes'), 'description': _('Focus reporting on decisions, customer value, and operational improvement.')},
]

RESOURCES = [
    {'type': _('Guide'), 'title': _('A practical guide to multilingual campaign operations'), 'description': _('Learn how to organise translation, review, and local approval without slowing every launch.')},
    {'type': _('Article'), 'title': _('Five signs your campaign workflow needs attention'), 'description': _('Spot avoidable handovers, unclear ownership, and reporting that arrives too late.')},
    {'type': _('Template'), 'title': _('Campaign launch readiness checklist'), 'description': _('Use a simple checklist to confirm content, data, approvals, and support are ready.')},
    {'type': _('Webinar'), 'title': _('Designing calm marketing operations'), 'description': _('See how focused workflows can reduce coordination effort and improve decision quality.')},
    {'type': _('Case study'), 'title': _('How Alpine Works reduced launch delays'), 'description': _('A regional team created one visible process for briefs, localisation, and approval.')},
    {'type': _('Report'), 'title': _('The state of connected customer work'), 'description': _('Explore common coordination challenges and the practices teams use to address them.')},
]

LOCALISATION_DEMO_COPY = [
    _('Latest updates'),
    _('View all activity'),
    _('Create campaign'),
    _('Invite team member'),
    _('Export report'),
    _('Last 30 days'),
    _('Completion rate'),
    _('Average review time'),
    _('Campaign reach'),
    _('Content approved'),
    _('Workspace health'),
    _('Good'),
    _('Action required'),
    _('No recent issues'),
    _('Review permissions'),
    _('Manage integrations'),
    _('Download data'),
    _('Help centre'),
    _('Product updates'),
    _('Contact support'),
    _('Your changes were saved.'),
    _('This action cannot be undone.'),
    _('Select a language to preview the translated experience.'),
    _('The demo stores your language choice in the session.'),
    _('Backend messages use the same translation catalogues as the templates.'),
    _('Short labels and long sentences are both included in the example.'),
    _('Translations can be updated without changing the application logic.'),
    _('Use the extraction command after adding new source strings.'),
    _('Compile the catalogues before deploying the application.'),
    _('Missing translations fall back to the English source text.'),
]

CATALOGUE = [
    _('A campaign owner changed the launch date.'),
    _('A practical guide to multilingual campaign operations'),
    _('A product specialist will reply within two business days.'),
    _('A quick view of your current workspace activity.'),
    _('A regional team created one visible process for briefs, localisation, and approval.'),
    _('About'),
    _('Action required'),
    _('Active campaigns'),
    _('Activity'),
    _('Adapt global campaigns while preserving local language, timing, and compliance needs.'),
    _('Advanced automation'),
    _('All rights reserved.'),
    _('Apply customer preferences consistently across channels and campaign steps.'),
    _('Article'),
    _('At risk'),
    _('Audience builder'),
    _('Audit export'),
    _('Average review time'),
    _('Backend messages use the same translation catalogues as the templates.'),
    _('Book a demo'),
    _('Bring selected data into the workspace through transparent, manageable connections.'),
    _('Build better customer journeys with one connected workspace.'),
    _('Campaign launch readiness checklist'),
    _('Campaign planning'),
    _('Campaign reach'),
    _('Cancel'),
    _('Case study'),
    _('Choose the capabilities that match your current priorities.'),
    _('Clarity over noise'),
    _('Close'),
    _('Company'),
    _('Compile the catalogues before deploying the application.'),
    _('Completion rate'),
    _('Connect activity to outcomes with understandable reports for every stakeholder.'),
    _('Connected capability'),
    _('Consent controls'),
    _('Contact'),
    _('Contact support'),
    _('Content approved'),
    _('Content library'),
    _('Coordinate briefs, channels, owners, and launch dates in one shared view.'),
    _('Core workflows'),
    _('Create a useful customer view without hiding the source of each data point.'),
    _('Create campaign'),
    _('Create reliable review paths for increasing volumes of regional content.'),
    _('Custom dashboards'),
    _('Customer profiles'),
    _('Customer welcome series'),
    _('Dashboard'),
    _('Data connectors'),
    _('Dedicated success manager'),
    _('Define practical segments with readable rules your team can review together.'),
    _('Designing calm marketing operations'),
    _('Download data'),
    _('Email support'),
    _('English'),
    _('Enterprise'),
    _('Error'),
    _('Every plan includes secure hosting, product updates, and multilingual support.'),
    _('Everything your team needs to plan, launch, and improve digital experiences.'),
    _('Experiment tracking'),
    _('Explore common coordination challenges and the practices teams use to address them.'),
    _('Export report'),
    _('Filter'),
    _('First name'),
    _('Five signs your campaign workflow needs attention'),
    _('Flexible plans for growing teams and established organisations.'),
    _('Focus reporting on decisions, customer value, and operational improvement.'),
    _('For growing teams coordinating multiple campaigns.'),
    _('For organisations with advanced governance needs.'),
    _('For small teams testing a connected workflow.'),
    _('Free trial'),
    _('French'),
    _('German'),
    _('Get started'),
    _('Give agencies and suppliers the context they need without exposing everything.'),
    _('Give local teams flexibility while keeping shared standards easy to follow.'),
    _('Good'),
    _('Growth'),
    _('Guide'),
    _('Help centre'),
    _('Home'),
    _('How Alpine Works reduced launch delays'),
    _('How can we help?'),
    _('Improve customer relevance'),
    _('Invite team member'),
    _('Italian'),
    _('Keep feedback, approvals, and final decisions attached to the work itself.'),
    _('Language'),
    _('Last 30 days'),
    _('Last name'),
    _('Latest updates'),
    _('Launch campaigns faster'),
    _('Learn how to organise translation, review, and local approval without slowing every launch.'),
    _('Learn more'),
    _('Loading'),
    _('Local markets'),
    _('Local markets online'),
    _('Make policies actionable with embedded checks, ownership, and evidence.'),
    _('Manage integrations'),
    _('Measure useful outcomes'),
    _('Meet the people building a calmer way to manage digital growth.'),
    _('Menu'),
    _('Message'),
    _('Missing translations fall back to the English source text.'),
    _('Monthly'),
    _('Needs review'),
    _('New'),
    _('No credit card required'),
    _('No recent issues'),
    _('Northstar Cloud'),
    _('Northstar Cloud brings campaigns, customer data, and team workflows together.'),
    _('Notifications'),
    _('On track'),
    _('Open reviews'),
    _('Organise approved messages, images, and reusable campaign components.'),
    _('Our principles'),
    _('Overview'),
    _('Page not found'),
    _('Partner workspace'),
    _('Performance insights'),
    _('Platform'),
    _('Please complete all required fields.'),
    _('Please enter a valid email address.'),
    _('Please try again later.'),
    _('Popular'),
    _('Practical ideas for modern marketing and customer experience teams.'),
    _('Pricing'),
    _('Priority support'),
    _('Privacy'),
    _('Product updates'),
    _('Projects'),
    _('Read the guide'),
    _('Recommended'),
    _('Record hypotheses, variants, decisions, and lessons in one consistent format.'),
    _('Reduce manual handovers with clear triggers, checks, and notifications.'),
    _('Regional brand update'),
    _('Replace scattered status meetings with a shared launch plan and visible ownership.'),
    _('Report'),
    _('Resources'),
    _('Responsible growth'),
    _('Return home'),
    _('Review cycles'),
    _('Review permissions'),
    _('Save'),
    _('Scale content operations'),
    _('Search'),
    _('See how focused workflows can reduce coordination effort and improve decision quality.'),
    _('Select a language to preview the translated experience.'),
    _('Settings'),
    _('Short labels and long sentences are both included in the example.'),
    _('Sign in'),
    _('Sign out'),
    _('Single sign-on'),
    _('Solutions'),
    _('Solutions for teams that want measurable progress without unnecessary complexity.'),
    _('Something went wrong'),
    _('Spot avoidable handovers, unclear ownership, and reporting that arrives too late.'),
    _('Spring product launch'),
    _('Standard reporting'),
    _('Start with a focused use case and expand when your team is ready.'),
    _('Starter'),
    _('Status'),
    _('Strengthen governance'),
    _('Submit'),
    _('Success'),
    _('Support local teams'),
    _('Tasks due this week'),
    _('Team'),
    _('Tell us what you are trying to improve.'),
    _('Template'),
    _('Terms'),
    _('Thank you, %(name)s. Your message has been received.'),
    _('The Italian landing page is ready for final review.'),
    _('The contact form is a demonstration and does not send email.'),
    _('The demo stores your language choice in the session.'),
    _('The page you requested does not exist.'),
    _('The state of connected customer work'),
    _('This action cannot be undone.'),
    _('This week'),
    _('Three approvals are waiting for your decision.'),
    _('Today'),
    _('Translations can be updated without changing the application logic.'),
    _('Unlimited users'),
    _('Up to 25 users'),
    _('Up to 5 users'),
    _('Updated %(minutes)s minutes ago'),
    _('Use a simple checklist to confirm content, data, approvals, and support are ready.'),
    _('Use customer context to make each interaction more useful and less repetitive.'),
    _('Use the extraction command after adding new source strings.'),
    _('Use this sample dashboard to demonstrate translated backend-generated content.'),
    _('Useful by default'),
    _('View all activity'),
    _('View details'),
    _('Warning'),
    _('We combine product thinking, service design, and responsible technology.'),
    _('We design features around real tasks instead of impressive-looking complexity.'),
    _('We explain how work moves, who decides, and what happens next.'),
    _('We help teams improve performance while respecting people, data, and local context.'),
    _('Webinar'),
    _('Welcome back'),
    _('Work email'),
    _('Workflow automation'),
    _('Workspace health'),
    _('Yearly'),
    _('Yesterday'),
    _('Your changes were saved.'),
    _('Your workspace'),
    _('per month'),
]
